### ISSUE TITLE
Move host details to its own page in MTV UI

### ISSUE THREAD

**Issue by vconzola** [konveyor/virt-ui#11]
We should move host details from a row expansion under providers to its own page that can be drilled down to from the providers page. Reasons: scaling - we need to support 50 or more hosts on a single provider and row expansion does not work well.

**Comment by mturley** [comment]
@ibolton336 this page should be at a new sub-route under providers with the provider id param in the URL, something like `/providers/:providerId` or `/providers/:providerId/hosts` (with a redirect from `/providers/:providerId`). You can use `useParams` from react-router-dom to grab that `:providerId` from the matched URL. You can see how I did that in https://github.com/konveyor/mig-ui/pull/1007
