### ISSUE TITLE
Button text for creating mappings/plans should always say "Create" and not "Add [plan|mapping]"

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#111]
We have this text wrong in a few places (it's wrong in the mockups too, confirmed this is the intention with @vconzola)

**Comment by gildub** [comment]
@mturley, I can find only "Add" button for Mapping, did I miss something?

**Comment by mturley** [comment]
I don't think you missed something, I think I just phrased the issue in a confusing way, I meant to express they should be consistent. I think you're right that only mappings needed to be changed.
