### ISSUE TITLE
Incorporate ResourcesEmptyIcon in the pipeline summary component once it is available in PF

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#115]
Upstream issue: https://github.com/patternfly/patternfly-react/issues/4979
We may want to create our own issue to use before there is one available in PF.

**Comment by gildub** [comment]
@mtruley FYI upstream PF has been updated https://github.com/patternfly/patternfly/issues/3624.
Now waiting to be integrated into downstream release.

**Comment by mturley** [comment]
Awesome, thanks for following that @gildub . I think as soon as they bump the `@patternfly/patternfly` version in `@patternfly/react-code` it should be picked up automatically
