### ISSUE TITLE
Follow up when VM `concerns` array `severity` types are finalized

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#126]
Right now the `concerns` array on an `IVMwareVM` has objects with `severity` values assumed to be one of `'Warning' | 'Critical' | 'Advisory' | 'Info'`. We should follow up and make sure the possible values there are correct when @jortel has them finalized, and double check the logic in the `VMConcernsIcon` and `VMConcernsDescription` components.

**Comment by mturley** [comment]
Also, when each concern has a `description` and `remedy` we should render those in `VMConcernsDescription` in addition to the `concern.name`.

**Comment by mturley** [comment]
Related: https://github.com/konveyor/virt-ui/issues/238

**Comment by gildub** [comment]
I asked Jeff for an update as of today.

**Comment by gildub** [comment]
The design document has been updated, the only possible values are Advisory, Warn and Critical.
Therefore we need to remove Info and replace Warning with Warn.
![concerns](https://user-images.githubusercontent.com/1901741/100112680-ce296900-2e6f-11eb-9945-b2ed48d0f3fe.png)

**Comment by gildub** [comment]
Actually we don't have to change Warning, Jeff is fixing the inventory so it uses Warning.

**Comment by gildub** [comment]
Jeff confirms it has been merged, so we're aligned with inventory controller.

**Comment by mturley** [comment]
Thanks for following up on this @gildub !
