### ISSUE TITLE
Make titles consistently sentence case / title case?

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#130]
@vconzola, in your mockups you have "Migration plans" (lowercase P) in the nav and the plans page title, but "Create Migration Plan" (all capitalized) in the wizard title. Should we make these consistent and use sentence case for all of them?

In the UI now I think we are already wrong about this in a few places. We should go over all our titles and make sure they are cased consistently.

**Comment by vconzola** [comment]
@mturley Crap. I'll go through and make a list of places where titles need to change. Current guidance is headline case in navigation and sentence case elsewhere.
