### ISSUE TITLE
Add filter for status column of VMMigrationDetails

### ISSUE THREAD

**Issue by gildub** [konveyor/virt-ui#146]
Following with https://github.com/konveyor/virt-ui/pull/142 adding a filter to the status column could be done post beta version.

**Comment by gildub** [comment]
@vconzola, my concern is in the case of a running migration we don't display that state explicitly in status line above the pipeline summary, and therefore looks awkward to me to filter on something we don't display. But I suppose that could be documented.
What do you think?

![status](https://user-images.githubusercontent.com/1901741/96847921-0ba36c80-1454-11eb-855e-d4a8ba9d7dbb.png)

**Comment by vconzola** [comment]
@gildub I wasn't thinking anything that complicated. :-) was just hoping to filter the status by Not started, In progress, and Completed so users can see which VMs are still migrating during plan execution.
