### ISSUE TITLE
Look into proxying inventory and host cluster APIs through Express to avoid SSL/CORS errors

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#152]
Based on a discussion with @fdupont-redhat, it seems like making our inventory and cluster API requests from the NodeJS side instead of the browser side could circumvent the SSL cert errors we have to show the user and prevent them from having to accept self-signed certs themselves, etc. We could just proxy `/api/inventory/*` and `/api/cluster/*` or whatever through Express to point to the real endpoints and then the browser would do everything through the single origin.

**Comment by mturley** [comment]
In order to prevent the same self-signed cert issues from blocking the proxied requests in Node, we'll need the operator to generate a CA cert file that we can point Node to. There are multiple ways to do this but I think the simplest would be to use the `NODE_EXTRA_CA_CERTS` environment variable. https://medium.com/trabe/monkey-patching-tls-in-node-js-to-support-self-signed-certificates-with-custom-root-cas-25c7396dfd2a

**Comment by fdupont-redhat** [comment]
Already done in https://github.com/konveyor/virt-operator/pull/22. It provides the self-signed CA certificates for:

- openshift-service-serving-signer@xxxxxxxxxx that signs the services internally
- ingress-operator@xxxxxxxxxx that signs the routes when using OpenShift generated certs
- *.apps.cluster-xxx.example.com, signed by ingress-operator for all the other applications exposed by a route

If Node proxies internal services, we don't even need these because our service are not using TLS internally. It is the ingress service that provides TLS termination, but then inside the namespace the traffic is unencrypted.

We can change that by using [service serving certificates](https://docs.openshift.com/container-platform/4.6/security/certificates/service-serving-certificate.html) to provide a certificate to each service: inventory, xavier-analytics, UI, for added security. The concerned services will require the following changes:

  - pod: listen on 8443 and use cert/key provided in a secret
  - service: listen on 8443 and forward traffic to 8443
  - operator: annotate the service to generate service serving certificate secret
  - operator: update deployment to mount the service service certificate secret in the pod

**Comment by fdupont-redhat** [comment]
I've created the following PRs to enable TLS for the inventory container, service:

- https://github.com/konveyor/controller/pull/29
- https://github.com/konveyor/virt-operator/pull/29

If you implement the proxy, you can point directly to the internal service: https://inventory:8443 and the TLS validation should work as the `NODE_EXTRA_CA_CERTS` variable already points to the CA certificates store.

**Comment by mturley** [comment]
Nice! yeah, we'd still need the proxy to take advantage of this, because I don't think we can ship that CA to the browser and inject it (nor should we, probably). This is great, it sounds like the simplest solution is just to proxy to internal services and not bother with TLS at that layer, but we can still provide Node with the certs in case we need them in the future, we may as well if they're there.

**Comment by mturley** [comment]
Removing the post-beta label, we should do this ASAP.

**Comment by fdupont-redhat** [comment]
From the list of APIs in virtMeta.json, the following internal endpoints can be used by the proxy:

- inventoryApi - http://inventory.openshift-migration.svc.cluster.local
- inventoryPayloadApi - http://inventory-payload.openshift-migration.svc.cluster.local:8080
- clusterApi - https://api.openshift-apiserver.svc.cluster.local

For HTTPS services, the CA certficates are in the `/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt` file.

**Comment by gildub** [comment]
Actually the inventoryPayloadApi is service is secured has it doesn't require authentication.
This leaves the payload open in the wild.
Although an overall solution would to secure the service it could work with this proxy solution by being restricted only virt-ui pod or at most to internal 'virt' network.

**Comment by gildub** [comment]
Mike and myself looked at the available packages to help implement this and we choose to use [http-proxy-middleware](https://www.npmjs.com/package/http-proxy-middleware) because of its powered by http-proxy which makes it easily to integrate within express as a middleware.

**Comment by gildub** [comment]
@fdupont-redhat, @mturley, with the backend having now SSL free endpoints, we don't have to worry about `NODE_EXTRA_CA_CERTS` to point CA certificates.

**Comment by fdupont-redhat** [comment]
The `NODE_EXTRA_CA_CERTS` environment is added by the operator, so you don't need to care about it in the Node configuration. And at least one internal service uses TLS: https://api.openshift-apiserver.svc.cluster.local. In https://github.com/konveyor/virt-ui/pull/214, I see that it sets `secure: false`, but it shoud be `true` in production.

I've also noticed in https://github.com/konveyor/virt-ui/pull/214 that the `target` is different in production and dev. Shouldn't it be set by virtMeta.json in every environment. In production, the value can be changed to the same values as the one that are hard coded. It's a small change in the operator to update the Config Map and [konveyor/virt-operator#39](https://github.com/konveyor/virt-operator/pull/39) implements it.

**Comment by mturley** [comment]
@fdupont-redhat I was assuming since the local URLs would always be the same that they should be hard-coded. But it does make sense to let them be configured in virtMeta either way.

As for `secure: false`, sorry, I assumed we wouldn't use TLS internally at all in prod.

**Comment by fdupont-redhat** [comment]
Well, the UI is actually configured to use TLS also internally and I've a PR opened to do the same for inventory. This will become the default pattern: HTTPS Everywhere.

Regarding, the hard coded URL, they can change based on the namespace where the operator is installed. It may not be `openshift-migration`.

**Comment by mturley** [comment]
Ok. Sounds good, we'll fix it. Thanks @fdupont-redhat

**Comment by gildub** [comment]
@fdupont-redhat, We'll use `virtMeta` since it becomes the reference and use `secure: true` (the default) for production.

**Comment by mturley** [comment]
We just need to also change the controller to put the `.local` URLs into virtMeta instead of the remote ones.

**Comment by mturley** [comment]
Per @fdupont-redhat , we should have the proxy middleware use `logLevel: 'debug'` if `process.env.DEBUG` is set, even in prod mode.

**Comment by gildub** [comment]
@mturley, good point. Just added it.
