### ISSUE TITLE
Text fields are limited to 20 characters

### ISSUE THREAD

**Issue by fdupont-redhat** [konveyor/virt-ui#156]
When creating a provider with the wizard, it complains that the username is longer than 20 characters and keeps the _Add_ button greyed out. 

![image](https://user-images.githubusercontent.com/25821288/97152352-08b8bc80-1771-11eb-9abe-2493e382ec4c.png)

Given that the default VMware user is `administrator@vsphere.local` is longer than 20 characters, it doesn't sound as a reasonable limit. Even more as it won't be displayed in any table where it could break the alignment. A lot of users will have connected their vCenter to Active Directory and will use domain based names, such as `john.doe@my.too.deep.domain.tree`, hence more than 20 characters.

Would it be possible to extend the limit to 256 characters?

**Comment by mturley** [comment]
Ah, yep, we need to fix the validation criteria for all our forms. This was added just to test that validation was working. I intended to fix it as part of #60 but we missed it.

@fdupont-redhat I can open a PR for this specific example, but can you and/or @jortel help me identify what the actual field validation criteria should be for a lot of these CR properties? I know there are also specific limitations to what kinds of characters can be used in names, etc.

**Comment by mturley** [comment]
For now I'm removing all the character limits on these fields in #158 to resolve this, but I also opened #157 so we remember to add real accurate validations here.

**Comment by fdupont-redhat** [comment]
- Name: 32 characters should be enough for a short description. It depends on the size of the column in the table, no?
- Hostname: 255 characters according to [RFC 1035](https://www.freesoft.org/CIE/RFC/1035/9.htm).
- Username: 320 characters according to [RFC 3696](https://www.rfc-editor.org/rfc/rfc3696.txt), 64 before `@`, 255 after.
- Password: 256 characters for paranoids.

**Comment by mturley** [comment]
As far as sizes of columns, IMO we should allow whatever length the backend requires and have the UI flexible enough to make space for it, and if it has to wrap the name to multiple lines (while not ideal) it should be able to. @vconzola may disagree though.

For names of CRs, do you know what characters are and are not allowed? I think I saw some errors when I was trying to make a name with symbols in it.

**Comment by fdupont-redhat** [comment]
@mturley, here is the naming convention followed by Kubernetes: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/. I think that CR names follow the _DNS Label Names_ convention, i.e:
- contain at most 63 characters
- contain only lowercase alphanumeric characters or `-`
- start with an alphanumeric character
- end with an alphanumeric character

**Comment by mturley** [comment]
Perfect, thanks @fdupont-redhat ! I'll write a validation helper for that and apply it to all the relevant fields.

**Comment by fdupont-redhat** [comment]
If it doesn't already exists, it might be worth contributing the validator to Patternfly for other projects in OpenShift.

**Comment by mturley** [comment]
Yeah, that's not a bad idea. We're specifically using a library called `yup` for validation, so I'll likely make it a yup schema object, but that might be useful anyway for those who want to use that library. Maybe I'll just make it a plain JS function and plug that into yup so it's more reusable.

**Comment by vconzola** [comment]
@mturley I don't ever want to wrap text in a table cell. I'd rather use ellipses with a tooltip to show the entire name of something. Depending on what the content of the field is the ellipses can be trailing or centered.

**Comment by mturley** [comment]
@vconzola ah, right, sorry. Ellipses it is. Do you have an opinion on whether we artificially limit the length of plan/mapping names as well, or should they just be allowed to be as long as the API allows?

**Comment by vconzola** [comment]
@mturley I've seen too many times over the years when the UI limited something like this and it came back to bite us. I think we should just support what the API allows.

**Comment by mturley** [comment]
Sounds good to me.
