### ISSUE TITLE
Determine real requirements for form validation and add to form schemas

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#157]
We had some placeholder string min/max limits that were incorrect and only there for testing purposes, but I'm removing those to fix #156.

We need to figure out the actual requirements our text fields need to meet for submitting CRs and implement those validation rules for our forms properly. Character limits, disallowed characters, etc.

**Comment by mturley** [comment]
More info in the discussion here: https://github.com/konveyor/virt-ui/issues/156#issuecomment-716602147

**Comment by mturley** [comment]
@fdupont-redhat I'm applying your specifications for CR names and for the fields in the VMware provider form from https://github.com/konveyor/virt-ui/issues/156#issuecomment-716602147, but do you know what we should use for our other fields?

Here are the ones I'm not sure about:
* Migration plan description
* OpenShift cluster URL (I can use the JS `new URL()` constructor to verify that it complies with [RFC 3986](https://tools.ietf.org/html/rfc3986), just want to make sure that's accurate
* OpenShift service account token

**Comment by fdupont-redhat** [comment]
I'd say:

- Migration plan description: 64 alphanumeric characters
- OpenShift URL: RFC 3986 sounds good
- OpenShift service account token: I don't know. It's a very long string. @jortel any idea?

**Comment by fdupont-redhat** [comment]
> Only 64 for the description? it's presented as a multi-line text area

Well, then it can be longer. Something like 1024 to allow meaningful multi-line descriptions. What is usually allowed in Patternfly?
