### ISSUE TITLE
Remove Travis CI and use GitHub Actions for all CI?

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#176]
Travis CI has been pretty inconsistently reliable and sometimes will just entirely fail to pick up a PR, as we saw with #173 .

We are already using GitHub Actions for the preview deployments to Surge, and it is working reliably. It would be easy to just add `yarn ci` as a step in the existing workflow, or add another workflow file, and disable Travis (or at least mark it as not required). When we add Codecov (#166) we could also just do it via GitHub Actions (they even have a preconfigured action for it: https://github.com/marketplace/actions/codecov-action).

Thoughts @ibolton336 @gildub @fdupont-redhat ? I'm not sure if there's anything specific we're getting out of Travis that isn't provided by GH Actions.

**Comment by gildub** [comment]
@mturley, with recent failure of Travis on both virt-ui and mig-ui this is would be great sooner than later.
I can't see anything we have in Travis that Github Actions CI won't provide.

**Comment by ibolton336** [comment]
Huge +1 from me. Travis is consistently bogged down & is really hurting productivity.

**Comment by mturley** [comment]
Sounds good to me. It would be pretty trivial to add a GitHub Actions workflow for general CI. I think it should be a separate one from the one that deploys the previews, just in case surge.sh fails.

**Comment by mturley** [comment]
If one of you wants to, you just need to create another workflow file just like this one: https://www.github.com/konveyor/virt-ui/tree/master/.github%2Fworkflows%2Fdeploy-pr-preview.yaml

You can just remove all the action items except Checkout, Setup Node.js, and Install Dependencies, and then add one that runs `yarn ci`

Or I'll take care of it when I get back.

**Comment by gildub** [comment]
@mturley, that's exactly what I did.
