### ISSUE TITLE
Show time zone in rendered date/time strings for start/end times of migrations

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#185]
Feedback from @fdupont-redhat : it's unclear what time zone is being displayed in these rendered time stamps. They are converted to the browser's local time zone, but that isn't obvious, we should show the zone as well.

**Comment by fdupont-redhat** [comment]
I checked again and it's actually my browser's local time that is used. I'm wondering if adding more characters to start/end times is a good idea with regards to the column size and the space left for the pipeline. What is the minimal recommended screen resolution for the UI?

**Comment by mturley** [comment]
Good question, @vconzola do you know? I think that is largely under our control, we can always truncate columns with ellipses and show the full value on hover (like we do with errors on a pipeline step).

**Comment by vconzola** [comment]
@mturley I'm pretty sure that all of the UI Sketch templates are based on a resolution of 1500 x 900. the first breakpoint that changes page layout is at 1450 pixels. so @fdupont-redhat for a user to see the ui as designed the horizontal screen resolution needs to be > 1450 pixels. but as mike says we can limit column width as necessary and use truncated text with ellipses when text is longer than the column width. the one thing we want to avoid when at all possible is wrapping textin a table cell.

**Comment by mturley** [comment]
Format from mockups per @vconzola 

> For start and end times format should be: 
> 07 Jan 2020, 9:38:11 PM EST
