### ISSUE TITLE
Activate http-proxy-middleware secure flag in production, properly install CA cert instead 

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#187]
We turned off NodeJS TLS validation with this env in the Dockerfile in https://github.com/konveyor/virt-ui/pull/186, just as was done in mig-ui, to avoid errors when logging in on some clusters. We should find a better solution.

**Comment by mturley** [comment]
Equivalent in mig-ui: https://github.com/konveyor/mig-ui/issues/1055

**Comment by gildub** [comment]
This has now migrated to using secure flag for http-proxy-middleware.
See https://github.com/konveyor/virt-ui/pull/214 for details.
The question remains to use `secure: true` for production which is not likely to happen before post-beta.
Adjusting title accordingly.

**Comment by mturley** [comment]
I forgot about this issue @gildub . I think we actually don't want to use `secure` at all. In prod, we won't need SSL at all because the internal URLS (`http://*.local`) don't use HTTPS. And in dev, we'd be forcing the browser to accept self-signed certs anyway, so unless we want to all install the CA cert in our dev environments I think we can safely just use `secure: false` for developing too (I could be convinced otherwise on that one though).

**Comment by gildub** [comment]
@mturley, all good then if we don't need SSL between the virt-ui pod and the backend.
Closing this one.

**Comment by mturley** [comment]
@gildub oops. We should listen to Fabien on this, not me :) https://github.com/konveyor/virt-ui/issues/152#issuecomment-727904130
