### ISSUE TITLE
When creating a Migration CR, add `ownerReferences` pointing to the plan so that deleting the plan will delete the migration

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#190]
This should work according to @jortel and prevent us from having to manually find and delete the associated migrations when a plan is deleted.

Here's what I found in the k8s docs about owner references: https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#owners-and-dependents

Looks like what we need to do is add `metadata: { ownerReferences: [ { kind: 'Plan', name: 'my-plan' } ] }`

**Comment by gildub** [comment]
That's great, just need to add apiVersion and uid which are required:
`metadata: { ownerReferences: [ { kind: 'Plan', name: 'my-plan', apiVersion: 'virt.konveyor.io/v1alpha1', uid: '4e56c6f4-de55-4cca-bee0-559ff04557a4' } ] }``
