### ISSUE TITLE
Target networks need to be namespace-qualified

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#200]
It's possible to have two target networks show up in the mapping builder with the same name, since the names only have to be unique within their namespace and we can have networks in multiple namespaces.

We should display the namespace along with the network (either for all of them, or just for the ambiguous ones). Thoughts, @vconzola ?

**Comment by vconzola** [comment]
@mturley Yet another reason to get rid of extra-plan mappings altogether. I guess we can show them like path (namespace/network_name) in the dropdown. Hopefully, there will be room. We'll also need to add "(namespace/network_name)" to the the "Target networks" label in the heading.

**Comment by mturley** [comment]
I'm not seeing how getting rid of extra-plan mappings would help, since that doesn't limit the available target options (only the target provider choice does that). I'll see what it looks like with that namespace/network_name text.

**Comment by vconzola** [comment]
If mappings only exist in a plan, we don't need to worry about this because we're already selecting a target namespace in step 1 and we can filter target networks based on target namespace selection.

**Comment by mturley** [comment]
Ah, true.. I hadn't considered whether the migrated VMs and the NADs need to be in the same target namespace. Does it make sense to allow selecting target networks that aren't in the plan's target namespace @jortel ?

**Comment by mturley** [comment]
@vconzola even if we keep the extra-plan mappings, it sounds like we never want a mapping that mixes target networks from more than one target namespace. So maybe we should also select the target namespace when you create a mapping (and save that to the Mapping CRs as well).

**Comment by mturley** [comment]
@vconzola here's how it looks with the namespaces prepended:
![Screen Shot 2020-11-09 at 2 28 34 PM](https://user-images.githubusercontent.com/811963/98587282-e6a65a80-2297-11eb-87b0-d74ddeb7e612.png)

**Comment by vconzola** [comment]
@mturley If Jeff says it doesn't make sense to allow users to create a network mapping that spans target namespaces, then yes, we should add a namespace dropdown/filter to the mapping page. Put it under the Target provider field. This will make the UI look a little skewed, but that's the most logical place for it - disabled until provider is selected.

**Comment by mturley** [comment]
Sounds good. If that ends up being the case I'll also remove this "namespace /" prefix.

**Comment by mturley** [comment]
@vconzola I talked to Jeff and he says we do need to allow the user to select target networks in any namespace. So I think it makes sense to add the `/` qualifier like in this screenshot, and not add the target namespace field to the mapping form.

**Comment by vconzola** [comment]
@mturley This really doesn't make any sense to me. If a plan is namespace bounded, why would a mapping not be? This means if a user selects an existing mapping you'll have to filter it to show only those networks associated wit hthe target namespace for the plan. Seems unnecessarily complicated. Unless we're future-proofing for a time when a plan can include multiple target namespaces?

**Comment by mturley** [comment]
I don't need to filter the networks at all as far as I understand. The target namespace for the plan is selecting what namespace the VMs will be moved to, but VMs in one namespace can use a network in another namespace.
