### ISSUE TITLE
VM names display slashes (/) as "%2f".

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#202]
It seems like we need to run all the VM names through `decodeURIComponent`.

**Comment by gildub** [comment]
@mturley, is that not an issue coming down from the source of that data?
Of course it doesn't  hurt to decode name just in case.

**Comment by mturley** [comment]
That's fair enough. I'll open an issue on the controller instead.

**Comment by mturley** [comment]
Closing in favor of https://github.com/konveyor/virt-controller/issues/75.
