### ISSUE TITLE
Plans table: in actions dropdown, when Edit or Delete are disabled, add a tooltip explaining why

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#223]
Consistent with how we did it for the providers page.

**Comment by gildub** [comment]
@vconzola, in the case of the providers, the tooltip displays "This provider cannot be removed" or edited depending on the action selected. This is only reinforcing the what but that doesn't explain the why.
Wouldn't be more informative to display "This provider is currently used by a migration and cannot be removed/edited/etc" ?
