### ISSUE TITLE
[BZ#1901967] Add the ability to copy the ellipsis'd texts to clipboard with a button

### ISSUE THREAD

**Issue by fdupont-redhat** [konveyor/virt-ui#267]
If a VM migration fails, the related error message is truncated, and when hovering the mouse over it the full error is displayed in a tooltip (see screenshot below). However, it is not possible to select the text in the tooltip. This would be convenient when reporting bugs or opening support cases. So, it would be great to add the ability to copy the text to clipboard with a button.

![SMigrated_vm_error_message](https://user-images.githubusercontent.com/25821288/100367656-d49c1a00-3002-11eb-8af8-b070fdaf0011.png)

RHBZ: https://bugzilla.redhat.com/show_bug.cgi?id=1901967

**Comment by gildub** [comment]
@fdupont-redhat, I would consider this as a bug and more as a RFE.

**Comment by gildub** [comment]
@vconzola, please let us know your thoughts.
