### ISSUE TITLE
Evaluate form state libraries e.g. Formik, react-final-form, react-hook-form and add validation to our forms

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#40]
I figured we should have an issue like this to remind us that we currently aren't doing any form validation. At some point soon we should investigate solutions for this, and break down tasks for each form we need to add it to.

**Comment by gildub** [comment]
React Hook Form seems to me as the best solution between those form validation approaches:

* plain react:
  - Requires a fair amount of boilerplate for validation.
  - Makes sense for a project with a small amount of form/fields
  - Meanwhile for a bigger project, the use of a helper library make sense.

* formik:
 - Based upon React `Context`, `State`
 - Heavy re-rendering
 - We had issues with the latter 

* react-final-form: 
  - Similar approach to Formik, using `Context`, `State`. 
  - Documentation quite heavy and not very intuitive (at least to me!).
  - Formik has stronger support. Why use another Formik?

* react-hook-form: 
  - Based upon React Hooks and Ref
  - No component to import
  - Minimal re-rendering
  - Very straightforward approach, less code
  - Good documentation and intuitive (at least for me).
  - Active community

* react-hook-form vs formik 
https://react-hook-form.com/faqs/#ReactHookFormFormikorReduxForm

**Comment by mturley** [comment]
Looking more into this, it seems we can use https://github.com/jquense/yup as the validation component with or without any of these libraries. It seems like a really strong contender (1.5 million weekly downloads on npm) no matter what we choose to go with it

**Comment by gildub** [comment]
Capturing latest thoughts that came from recent discussions:

With `Yup`, the schema approach is really solid, no wonder why so many other libs are using it or having a plug-in option for it.

Although `Yup` allows to create very detailed and customized validations, it doesn't takes away the need to track down every form field for validation, that means potentially lots of boilerplate and this is where solution like Formik become handy.

In (basic example)[https://github.com/gildub/virt-ui/blob/yup/src/app/Providers/components/AddProviderModal/AddProviderModal.tsx#L41-L74] we can see how form validation can be very straightforward and which we could use. When a field depends from another one, or validating a URL, or checking backend status on selected object are actions we could keep wrapped under a given form' schema.

**Comment by gildub** [comment]
Also after experimenting a little bit with React Hook Form a couple of first impressions:
  - A ref needs to be passed down to all the PF form components. It's not clear at this stage what type needs to be passed to make it work.
  - Using non connected components seems counter productive to React pattern. Although React Hook Form "controller" could be use as a wrapper to have controlled components, it probably defeat the gain initiated by React Hook Form.

**Comment by mturley** [comment]
As far as React Hook Form is concerned, I think I would be inclined to try it if it weren't for PatternFly's form components being designed to be used as controlled. It sounds like using the required refs and types would be a headache there and require upstream changes. I'm leaning much more towards a homebrew solution or Formik.

I'm in the process of working on a small custom hook that we could use instead of Formik, I'm hoping to share that tomorrow to help us make a decision. But I'd be fine with not using it.
