### ISSUE TITLE
Change selection state isEqual functions to use UID instead of name

### ISSUE THREAD

**Issue by ibolton336** [konveyor/virt-ui#41]
When using mikes useSelectionState hook, the isEqual function (used to check for selected state in an immutable data structure https://konveyor.github.io/lib-ui/?path=/docs/hooks-useselectionstate--checkboxes) needs a unique ID to check against. We should move to UID's here. This will require deciding how we want to generate UIDs for providers, plans, and mappings mock data until we have real data from the api.

**Comment by mturley** [comment]
@ibolton336 is this still important? I think in our context we can't have two resources of a kind with the same name, so they are unique enough.

**Comment by ibolton336** [comment]
Ok - I am fine with closing if that is the case.
