### ISSUE TITLE
Prevent empty source dropdowns in the mapping builder: when all sources are exhausted, the Add button should be disabled.

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#42]
@vconzola should we maybe show a popover indicating why the button is disabled?

**Comment by vconzola** [comment]
@mturley Maybe not necessary, but it couldn't hurt if it's a few lines of code. Text should be, "All source networks/datastores have been mapped."

**Comment by mturley** [comment]
@gildub one thing I realized here is that since the user can add multiple empty mapping items, if the logic is simply "disable button if no non-selected available sources remain" then it's still possible to end up with empty items with empty dropdowns, if they were added before the sources were exhausted.

So the logic should probably be "disable the button if the number of non-selected available sources is <= the number of mapping items with no source selected".

**Comment by vconzola** [comment]
@mturley ...or we could prevent the user from adding multiple empty mapping items. I didn't notice before that's possible. Why is the Add button not disabled until the user selects a source and target? Is that more difficult to code?

**Comment by mturley** [comment]
Fair point @vconzola . I don't know if we expect the user to select both for each one before adding the other, technically as it is now you can select all your sources and then select all your targets, or vice versa. We can limit it to having to select both for each group before adding another.

**Comment by vconzola** [comment]
The only downside (and maybe this isn't even a downside) to forcing the user to select source-target at once is the tooltip text for the Add button will need to be conditional. If the button is disabled because a source and target haven't been selected it will say, "You must select a source and target before adding another mapping."

**Comment by mturley** [comment]
Yeah, that's fine. Conditional rendering is what React is good at :)

**Comment by mturley** [comment]
@gildub have you started on this yet? I was going to add form validation to the mapping builder, it might be easier for me to just knock this out while I'm in there so we avoid conflicts. If you already started working on it I'll wait.

**Comment by gildub** [comment]
@mturley, I've an initial toggle disabling the `add` button when the list of options has been exhausted, I just rebased and pushed it.

Meanwhile there is an issue with the `Remove all` button which seems to be related to duplicated react component (sharing the same key) in the MappingBuilder. I believe we need to address that before continuing.

**Comment by gildub** [comment]
@mturley, obviously that's not enough. I'll come back to it, unless you want to take over. Thanks

**Comment by mturley** [comment]
Ok, in that case let me know if you come back to it, and I'll let you know if I get to it first?

**Comment by vconzola** [comment]
@mturley @gildub Here's a [tooltip mockup](https://drive.google.com/file/d/1G_dQmKjE6rDkslDFL-3WLPufFCjJiNe9/view?usp=sharing) for the Add button when the list of sources is exhausted.

**Comment by vconzola** [comment]
@mturley @gildub ...and here's a [tooltip mockup](https://drive.google.com/file/d/1LSLuQcOgkZAhXXW8hXtEry5sQEaI8E00/view?usp=sharing) for the Add button when a source and target haven't been selected.

**Comment by mturley** [comment]
Perfect, thanks @vconzola
