### ISSUE TITLE
Remove tooltip on "Create migration plan" button in empty state

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#46]
I think this was carried over from CAM code. @vconzola can you confirm whether we want this?

<img width="705" alt="Screen Shot 2020-09-14 at 10 47 15 AM" src="https://user-images.githubusercontent.com/811963/93105368-fd0bad80-f67c-11ea-8198-05fe1d82c8bc.png">

**Comment by vconzola** [comment]
@mturley The button label is pretty self explanatory. I don't think we need a tooltip.
