### ISSUE TITLE
Clean up console errors/warnings when navigating to plans tab

### ISSUE THREAD

**Issue by ibolton336** [konveyor/virt-ui#52]
I think we need to add some missing labels to fix this. 

![image](https://user-images.githubusercontent.com/11218376/93397916-8e7b4b00-f848-11ea-9165-b0e334801d89.png)

**Comment by gildub** [comment]
This is going to be obsolete as the modal wrapping the wizard is replaced by "in-page" wizard.
BTW the error is because the modal in question needs to have an `aria-label` property.
