### ISSUE TITLE
Move plan wizard from a modal to a standalone page w/ breadcrumb bar

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#54]
Discussing form validation with @vconzola, we realized there may be a few things we want to warn the user about actively before they proceed to the next step (e.g. open a modal that says "not all source datastores were mapped, are you sure you want to proceed?")

In order to prevent having a modal on top of a modal, we decided we should convert the plan wizard into a full page. This is low priority though, we can have a modal-in-a-modal in the meantime if we need to.

**Comment by gildub** [comment]
@ibolton336, sorry, I realized after I pushed PR#95 that you assigned this one to yourself. Let me know if you prefer to keep your approach instead.

**Comment by gildub** [comment]
@mturley, @vconzola and @ibolton336, the challenge with a in-page wizard is to warn the user that the wizard state would be lost if it navigates to another page.

Also, don't we need to add an explicit menu item for the wizard, more likely inside the "Migration plans" section?

**Comment by mturley** [comment]
@gildub Ian and I were talking about that (warning on leaving the wizard), there are a few ways to handle it, but I think it's manageable at a global level one way or another. We can open an issue to come back to that.

As for putting "create plan" or something in the top level nav menu, we could do that but we'd have to also have an item under that plans section for the plans table itself, because you can't navigate to the section parent (it's only an expandable control). I'll leave that up to @vconzola but I think it's ok to have it just accessible as a button in the plans page like we have today.
