### ISSUE TITLE
Implement plan status progress bar component

### ISSUE THREAD

**Issue by ibolton336** [konveyor/virt-ui#58]
_As a user I would like to view an individual plans migration progress so that I can determine the current status of a given migration/plan status._

This view includes a PF progress bar with several states derived from the plans underlying migration data. This component should be somewhat modular so that it can receive status information via props & change the components text, icon, & progress bar color accordingly. 

![image](https://user-images.githubusercontent.com/11218376/93526020-d5c71180-f904-11ea-87c8-82f467f95e42.png)

**Comment by gildub** [comment]
@ibolton336, the initial progress bar is already in https://github.com/konveyor/virt-ui/pull/66 but the right statuses and logic behind will be in the PR resolving this one.

**Comment by gildub** [comment]
@ibolton336, after discussing with @vconzola (https://github.com/patternfly/patternfly-react/issues/4875) it turns out that the icon is meant to be on the right end side.
