### ISSUE TITLE
Handle displaying various status conditions on providers

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#64]
The status column in the providers table will currently only display the first condition in the list, and hasn't been tested with error or warning conditions. We need to double check that stuff, and possibly look at the rest of the conditions array to identify the most serious condition or display multiple conditions.

See: https://github.com/konveyor/virt-ui/blob/2bf0b914669a79553bad324759b1985bd62a8e29/src/app/Providers/components/ProvidersTable/VMware/VMwareProvidersTable.tsx#L43

**Comment by ibolton336** [comment]
+1 This will be a common theme across all of the API resources. With CAM, we have functions that short circuit & return a status when a condition is met. The critical/severe error state statuses are at the top of the function block. We should think about the best way to do this across the app.

**Comment by mturley** [comment]
Yep. I imagine the status condition API structure will be common across multiple API objects, so we could make a common component to consume/display that.

**Comment by gildub** [comment]
We effectively need to deal with categories before displaying a status type:
```
Condition categories:
Advisory - An advisory condition provides information that does not impact a resource’s Ready condition.
Warn - A warning condition alerts users to concerns that do not impact a resource’s Ready condition.
Error - An error condition indicates a problem that is serious enough to prevent a resource from having a Ready condition but does not indicate that the resource itself is unhealthy.
Critical - A critical condition indicates a serious problem and that the resource is not healthy.  This blocks the Ready condition.
Required - A required condition represents something that is needed to have occurred or be true in order for the resource to have a Ready condition.
```
