### ISSUE TITLE
Add a FilterToolbar to the plans table

### ISSUE THREAD

**Issue by mturley** [konveyor/virt-ui#76]
Leaving this out of #66, let's add it as a follow-up. To the left of the Create button there should be a FilterToolbar (driven by useFilterState) to allow the user to filter by a few columns.

![Screen Shot 2020-09-23 at 2 31 21 PM](https://user-images.githubusercontent.com/811963/94054291-7a37d080-fda9-11ea-852b-6f2676607d12.png)

@vconzola which columns should we able to filter on here? I'm guessing all of them except number of VMs?

**Comment by vconzola** [comment]
@mturley Correct, filter by all columns except number of VMs.
