### ISSUE TITLE
Implement empty state screen for the "Plans" view

### ISSUE THREAD

**Issue by ibolton336** [konveyor/virt-ui#8]
Create the empty state & parent component for the "Plans" view. This page will display an empty state when no plans are currently loaded into the UI. 

![image](https://user-images.githubusercontent.com/11218376/91188103-e9dd7180-e6be-11ea-8c7e-a5f7aca399c1.png)

https://docs.google.com/presentation/d/1YtiJKf5FyDhBf_eIc6pXbHloCSidDmBKATgYXRtPh-o/edit#slide=id.g878b3b7f84_0_68

**Comment by mturley** [comment]
Huh, not sure why this wasn't auto-closed by #14. You used a magic word there. 🤷‍♂️
